version: '3.8'
services:
  web:
    image: berauto-app:latest
    build:
      context: .
      dockerfile: BerAuto/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=CarRentalDB;User Id=admin;Password=test123;TrustServerCertificate=True
